# adapté de https://dev.to/alissonzampietro/the-amazing-journey-of-docker-compose-17lj
version: '3.8'
services:
    api-service:
        build: .
        volumes:
            - ./api/:/usr/src/app/
        ports:
            - 5000:5000
        environment:
            PORT: 5000
            FLASK_DEBUG: 1
    mariadb:
        image: mariadb:10.5
        container_name: mariadb_partiel
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mydatabase
            MYSQL_USER: maria
            MYSQL_PASSWORD: maria
        volumes:
            - ./mariadb:/var/lib/mysql
    adminer:
        image: adminer
        container_name: adminer_partiel
        depends_on: 
            - mariadb
        ports:
            - 8080:8080